### ISSUE TITLE
No Treasure Maps datapack is incomplete

### ISSUE THREAD

**Issue by kaxonomy** [DMBuce/bucepack#3]
Please add full support so that it works for:
shipwreck_supply
shipwreck_treasure
underwater_ruin_big
underwater_ruin_small
and removes/replaces cartographer treasure map trades.

**Comment by DMBuce** [comment]
AFAICT, only the map chests in shipwrecks contain treasure maps. Shipwreck supply and treasure chest loot tables don't contain a treasure map entry like shipwreck map chests do.

Including treasure barrels in cartographer trades would make diamonds and hearts of the sea renewable, so I have no plans to add support for that. In vanilla worldgen, players who experience [MC-218156](https://bugs.mojang.com/browse/MC-218156) with cartographer trades can work around the issue by breeding new cartographers in locations where the bug isn't present.

I am pushing a change with underwater ruins support shortly. It will be included in the next release.

**Comment by kaxonomy** [comment]
How about removing the treasure map trades from cartographers and not replacing them with the barrel?

**Comment by DMBuce** [comment]
According to the wiki, cartographers only trade ocean explorer maps and woodland explorer maps. They lead to ocean monuments and woodland mansions respectively. The maps they sell aren't treasure maps leading to buried treasure, so AFAIK they shouldn't be affected by [MC-218156](https://bugs.mojang.com/browse/MC-218156).

Do you want the ocean maps or woodland maps to be removed, or both? Why do you want maps to be removed from cartographer trades? What is the use case for that feature?
